name: Build and push

on:
  workflow_dispatch:
      inputs:

        version_major:
          description: 'AlmaLinux major version'
          required: true
          default: '9'
          type: choice
          options:
            - 9

        application:
          description: 'Application name'
          required: true
          default: 'pico'
          type: choice
          options:
            - pico
            - nginx
            - apache_lua

env:
  # Latest version
  version_latest: 9

  # Platforms common list
  platforms: 'linux/amd64, linux/ppc64le, linux/s390x, linux/arm64'

  # Registries list:
  registries: 'quay.io/ykohut'

jobs:
  build-test-push:
    name: Deploy ${{ inputs.version_major }} ${{ matrix.image_types }} images
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # Set image types matrix based on boolean inputs.type_* with true value
        image_types: ${{ fromJSON(format('["{0}"]', inputs.application)) }}

    steps:

      -
        name: Prepare AlmaLinux Minor version number and platforms list
        run: |
          # AlmaLinux Minor version number and platforms list
          platforms="${{ env.platforms }}"
          case ${{ inputs.version_major }} in
            8)
              version_minor=".10"
              platforms="${platforms}, linux/386"
              ;;
            9)
              version_minor=".5"
              platforms="${platforms}, linux/386"
              ;;
            10)
              version_minor=".0"
              platforms="${platforms}, linux/amd64/v2"
              ;;
            10-kitten)
              version_minor=
              platforms="${platforms}, linux/amd64/v2"
              ;;
            *)
              echo "Almalinux ${{ inputs.version_major }} is not supported!" && false
          esac
          echo "version_minor=${version_minor}" >> $GITHUB_ENV
          echo "platforms=${platforms}" >> $GITHUB_ENV

      -
        name: Prepare date stamp
        id: date_stamp
        run: |
          # date stamp
          date_stamp=$(date -u '+%Y%m%d')
          echo "date_stamp=${date_stamp}" >> $GITHUB_ENV

      -
        name: Generate list of images to use as base name for tags
        run: |
          # list of registries to push to
          REGISTRIES="${{ env.registries }}"

          IMAGE_NAMES=
          # generate image names in format $REGISTRY/almalinux or $REGISTRY/${{ inputs.version_major }}-${{ matrix.image_types }}
          # image names are used by docker/metadata-action to set 'images'
          for REGISTRY in ${REGISTRIES//,/ }; do
            IMAGE_NAMES="${IMAGE_NAMES} $REGISTRY/${{ inputs.version_major }}-${{ matrix.image_types }}"
          done

          # remove space at the beginning of string
          IMAGE_NAMES=${IMAGE_NAMES# }
          # separate with comma instead of space and export to the action
          echo "IMAGE_NAMES=${IMAGE_NAMES// /,}" >> $GITHUB_ENV

      -
        name: Enable containerd image store on Docker Engine
        run: |
          # JQ file to switch into containerd image store
          cat << EOF > containerd-snapshotter.jq
          .features |= . + { "containerd-snapshotter": true }
          EOF
          sudo sh -c 'jq -n -f containerd-snapshotter.jq > /etc/docker/daemon.json'
          sudo systemctl restart docker
          docker info -f '{{ .DriverStatus }}'

      -
        name: Checkout ${{ github.repository }}, branch 'main'
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Quay.io
        if: contains(env.registries, 'quay.io')
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_CLI_PASSWORD }}

      -
        name: Generate tags and prepare metadata to build and push
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base names for tags
          images: ${{ env.IMAGE_NAMES }}

          # list of tags
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ inputs.version_major }},enable=true
            type=raw,value=${{ inputs.version_major }}${{ env.version_minor }},enable=true
            type=raw,value=${{ inputs.version_major }}${{ env.version_minor }}-${{ env.date_stamp }},enable=true

      -
        name: Generate Dockerfile
        run: |
          # Find files matching the path mask '*/Containerfile.*' (i.e., in subdirectories),
          # sort them based on their filenames,
          # and then create a single space-separated string of their full paths.
          containerfiles_sorted=$(find {${{ inputs.version_major }},${{ matrix.image_types }},tests} -name Containerfile.\* -type f -printf '%f\t%p\n' 2>/dev/null | \
                                    sort -t$'\t' -k1,1 | \
                                    cut -d$'\t' -f2 | \
                                    paste -sd ' ' -)

          # Generate Dockerfile from the sorted list of '*/Containerfile.*'
          for containerfile in $containerfiles_sorted; do
            cat "$containerfile" >> Dockerfile
          done

          echo "[Debug]"
          cat Dockerfile

      -
        name: Build images
        id: build-images
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: ${{ env.platforms }}
          build-args: |
            VERSION=${{ inputs.version_major }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      -
        name: Test images
        id: test-images
        run: |
          # [Test]
          # Get CMD instruction's binary from the image
          CMD_EXECUTABLE=$(docker inspect --format='{{index .Config.Cmd 0}}' ${{ steps.build-images.outputs.digest }})
          [ -z "${CMD_EXECUTABLE}" ] && echo "CMD instruction is not set in the image!" && false

          platforms="${{ env.platforms }}"
          for platform in ${platforms//,/ }; do
            case $platform in
              linux/386)
                LD_LINUX_SO="/usr/lib/ld-linux.so.2" ;;
              linux/amd64)
                LD_LINUX_SO="/usr/lib64/ld-linux-x86-64.so.2" ;;
              linux/ppc64le)
                LD_LINUX_SO="/usr/lib64/ld64.so.2" ;;
              linux/s390x)
                LD_LINUX_SO= ;;
              linux/arm64)
                LD_LINUX_SO="/usr/lib/ld-linux-aarch64.so.1" ;;
            esac

            # Skip platforms where ELF Application Binary interface is not supported
            # (e.g., linux/s390x)
            [ -z "${LD_LINUX_SO}" ] && continue

            # Creates a writeable container layer over the image and get binaries.list from it
            container_name="test_${{ inputs.application }}_${{ inputs.version_major }}_${platform/\//_}"
            docker create --platform=${platform} --name ${container_name} ${{ steps.build-images.outputs.digest }} >/dev/null
            rm -f binaries.list
            docker cp ${container_name}:/tmp/binaries.list . >/dev/null
            docker rm -f ${container_name} >/dev/null

            echo "[Debug] Testing platform ${platform} binaries with ${LD_LINUX_SO}"
            for EXECUTABLE in $(cat binaries.list); do
              # Fail tests if no executables are in the list
              [ -z "${EXECUTABLE}" ] && false

              # Skip dynamic linker configuration tool (ldconfig) to be inspected by dynamic linker
              [ "${EXECUTABLE}" = "/usr/sbin/ldconfig" ] && continue

              if docker run --rm --platform=${platform} ${{ steps.build-images.outputs.digest }} ${LD_LINUX_SO} --list ${EXECUTABLE}; then
                echo "Checked ${EXECUTABLE} on platform ${platform}: OK"
              else
                echo "[Debug] Some shared libraries are missing for ${EXECUTABLE} in the image (platform ${platform}) !"
                false
              fi
            done
          done

      -
        name: Push images
        id: push-images
        uses: docker/build-push-action@v5
        with:
          provenance: false
          context: .
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
